version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  unittest-lint-codecov:
    parallelism: 1
    resource_class: xlarge
    working_directory: ~/repo
    docker:
      - image: python:3.10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            pip install -r docker/requirements-dev.txt
      - run:
          name: Black lint check
          command: |
            cd swifter && black --check .
      - run:
          name: Unit tests
          command: |
            coverage run -m unittest swifter/swifter_tests.py
      - run:
          name: Codecov report
          command: |
            coverage report -i && coverage html -i
            codecov --required || (sleep 5 && codecov --required) || (sleep 5 && codecov --required) || (sleep 5 && codecov --required) || (sleep 5 && codecov --required)
      - store_artifacts:
          path: htmlcov

workflows:
  version: 2
  build-and-test:
    jobs:
      - unittest-lint-codecov
